import Link from "next/link";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-parchment flex flex-col">
            <main className="flex-1 w-full max-w-[720px] mx-auto px-6 py-16">

                <Link
                    href="/login"
                    style={{ color: "#0066cc", fontSize: "14px", letterSpacing: "-0.224px" }}
                    className="hover:underline"
                >
                    ← Back
                </Link>

                <h1
                    className="mt-8 mb-2"
                    style={{
                        fontFamily: "SF Pro Display, system-ui, sans-serif",
                        fontSize: "40px",
                        fontWeight: 600,
                        lineHeight: "1.10",
                        letterSpacing: "0px",
                        color: "#1d1d1f",
                    }}
                >
                    Terms of Service
                </h1>
                <p
                    className="mb-10"
                    style={{
                        fontFamily: "SF Pro Text, system-ui, sans-serif",
                        fontSize: "14px",
                        fontWeight: 400,
                        letterSpacing: "-0.224px",
                        color: "#7a7a7a",
                    }}
                >
                    Last updated: May 12, 2026
                </p>

                <div className="flex flex-col gap-8">
                    <Section title="1. Acceptance of Terms">
                        <p>
                            By accessing or using AI Business Decision Simulation, you agree to be bound by these Terms of
                            Service. If you do not agree, you may not use the platform. Use is limited to students
                            and faculty of participating academic institutions.
                        </p>
                    </Section>

                    <Section title="2. Permitted Use">
                        <p>
                            The platform is provided exclusively for academic and educational purposes. You agree to:
                        </p>
                        <ul>
                            <li>Use the platform only for coursework assigned by your institution.</li>
                            <li>Not share access credentials with others.</li>
                            <li>Not attempt to reverse-engineer, scrape, or automate interactions with AI agents.</li>
                            <li>Not submit work generated by external AI tools as your own analysis.</li>
                        </ul>
                    </Section>

                    <Section title="3. Intellectual Property">
                        <p>
                            All case materials, simulation playbooks, and platform content are the property of the
                            respective institution or AI Business Decision Simulation. You may not reproduce or distribute
                            case content outside of the platform without written permission.
                        </p>
                    </Section>

                    <Section title="4. Student Submissions">
                        <p>
                            Your submitted analyses and session data may be reviewed by your professor for grading
                            purposes. By submitting, you grant AI Business Decision Simulation a limited license to store and
                            process your submission for report generation and platform improvement.
                        </p>
                    </Section>

                    <Section title="5. Disclaimers">
                        <p>
                            AI agent responses are generated by large language models and may not always be accurate
                            or complete. The platform is provided &quot;as is&quot; without warranties of any kind.
                            We are not responsible for decisions made based on simulated stakeholder information.
                        </p>
                    </Section>

                    <Section title="6. Termination">
                        <p>
                            We reserve the right to suspend or terminate access for violation of these terms or at
                            the request of your institution. Upon termination, your access to case sessions and
                            reports will be revoked.
                        </p>
                    </Section>

                    <Section title="7. Contact">
                        <p>
                            Questions about these terms may be directed to{" "}
                            <a href="mailto:legal@example.com" style={{ color: "#0066cc" }} className="hover:underline">
                                legal@example.com
                            </a>
                            .
                        </p>
                    </Section>
                </div>
            </main>

            <footer className="w-full pb-8 text-center">
                <p
                    style={{
                        fontFamily: "SF Pro Text, system-ui, sans-serif",
                        fontSize: "12px",
                        fontWeight: 400,
                        letterSpacing: "-0.12px",
                        color: "#7a7a7a",
                    }}
                >
                    © 2026 AI Business Decision Simulation
                </p>
            </footer>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div>
            <h2
                className="mb-3"
                style={{
                    fontFamily: "SF Pro Display, system-ui, sans-serif",
                    fontSize: "21px",
                    fontWeight: 600,
                    lineHeight: "1.19",
                    letterSpacing: "0.231px",
                    color: "#1d1d1f",
                }}
            >
                {title}
            </h2>
            <div
                style={{
                    fontFamily: "SF Pro Text, system-ui, sans-serif",
                    fontSize: "17px",
                    fontWeight: 400,
                    lineHeight: "1.47",
                    letterSpacing: "-0.374px",
                    color: "#1d1d1f",
                }}
                className="flex flex-col gap-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:flex [&_ul]:flex-col [&_ul]:gap-1"
            >
                {children}
            </div>
        </div>
    );
}
